server:
  port: 8001
spring:
  application:
    name: r2rAdaptor
  mvc:
    pathmatch:
      # 解决mapping.getPatternsCondition()返回null
      matching-strategy: ant_path_matcher
springdoc:
  api-docs:
    enabled: false

# https://spring.io/blog/2022/10/12/observability-with-spring-boot-3
# All traces should be sent to latency analysis tool
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 1GB
      max-history: 0